---
- hosts: webserver
  become: true
  tasks:
  - name: copy files
    copy:
      dest: /home/ansible/
      src: /home/ansible/scripts/docker.sh

  - name: install docker
    command: sudo sh /home/ansible/docker.sh

  - name: Copy daemon.json to docker
    copy:
      dest: /etc/docker/
      src: /home/ansible/daemon.json
  - name: Restart Docker
    command: sudo systemctl restart docker

  - name: Docker Login
    command: sudo docker login -u admin -p admin123 65.0.168.243:8085

  - name: Pull Image from Docker Private Repositary
    command: sudo docker pull 65.0.168.243:8085/jt:v1.0
    
  - name: Run a container
    command: sudo docker run -p 8080:8080 -d -name java-tomcat 65.0.168.243:8085/jt:v1.0 
